import { CardShape, PrintTemplate } from '../types/buffet';

export const TEMPLATES: PrintTemplate[] = [
  // --- Full 8.5" x 11" Menu Sheets & Signage ---
  {
    id: 'sheet-full-8.5x11',
    name: 'Full 8.5" × 11" Menu Sheet & Poster',
    code: 'MENU-8.5x11',
    shape: 'sheet-letter',
    widthIn: 8.5,
    heightIn: 11.0,
    cornerRadius: 0,
    cardsPerSheet: 1,
    columns: 1,
    rows: 1,
    description: 'Full page 8.5" × 11" menu sheet for multi-course banquet menus, buffet station overview boards, or single feature dish posters.',
    category: 'sheets',
  },
  {
    id: 'sheet-bar-8.5x11',
    name: 'Full 8.5" × 11" Bar & Beverage Menu',
    code: 'BAR-8.5x11',
    shape: 'sheet-letter',
    widthIn: 8.5,
    heightIn: 11.0,
    cornerRadius: 0,
    cardsPerSheet: 1,
    columns: 1,
    rows: 1,
    description: 'Full page 8.5" × 11" bar menu for cocktail lounges, wedding host bars, cash bars, and subsidized drink menus.',
    category: 'sheets',
  },
  {
    id: 'sheet-half-5.5x8.5',
    name: 'Half Page Menu 5.5" × 8.5"',
    code: 'MENU-5.5x8.5',
    shape: 'rectangle',
    widthIn: 5.5,
    heightIn: 8.5,
    cornerRadius: 0,
    cardsPerSheet: 2,
    columns: 2,
    rows: 1,
    description: '5.5" × 8.5" half-letter menu cards (2/sheet) for table place settings and drink lists.',
    category: 'sheets',
  },

  // --- Standard Buffet & Table Cardstock ---
  {
    id: 'std-card-3.5x2',
    name: 'Standard Cardstock 3.5" × 2.0"',
    code: 'CARD-3.5x2',
    shape: 'rectangle',
    widthIn: 3.5,
    heightIn: 2.0,
    cornerRadius: 0,
    cardsPerSheet: 10,
    columns: 2,
    rows: 5,
    description: 'Standard 3.5" × 2.0" business card format (10/sheet). Primary industry standard for standing card clips & place cards.',
    category: 'cards',
  },
  {
    id: 'std-card-portrait-2x3.5',
    name: 'Vertical Place Card 2.0" × 3.5"',
    code: 'CARD-2x3.5-V',
    shape: 'rectangle',
    widthIn: 2.0,
    heightIn: 3.5,
    cornerRadius: 0,
    cardsPerSheet: 8,
    columns: 4,
    rows: 2,
    description: 'Vertical 2.0" × 3.5" portrait format for tall buffet clip stands and seating markers.',
    category: 'cards',
  },
  {
    id: 'tent-card-3.5x4',
    name: 'Foldable Tent Card 3.5" × 4.0"',
    code: 'TENT-3.5x4',
    shape: 'tent',
    widthIn: 3.5,
    heightIn: 4.0, // 2.0" standing face when folded
    cornerRadius: 0,
    cardsPerSheet: 4,
    columns: 2,
    rows: 2,
    isFoldable: true,
    description: 'Foldable 3.5" × 4.0" tent card with center scoring line. Free-standing without clips on buffet lines.',
    category: 'tents',
  },
  {
    id: 'card-rounded-3.5x2',
    name: 'Rounded Corner Card 3.5" × 2.0"',
    code: 'CARD-R-3.5x2',
    shape: 'rounded-rect',
    widthIn: 3.5,
    heightIn: 2.0,
    cornerRadius: 12,
    cardsPerSheet: 10,
    columns: 2,
    rows: 5,
    description: 'Contemporary curved corners (12px radius) for sleek luxury hospitality presentation.',
    category: 'shapes',
  },

  // --- Adhesive Stickers & Boxed Lunch Labels ---
  {
    id: 'sticker-box-4x2',
    name: 'Boxed Lunch & Meal Sticker 4.0" × 2.0"',
    code: 'STK-4x2',
    shape: 'rounded-rect',
    widthIn: 4.0,
    heightIn: 2.0,
    cornerRadius: 6,
    cardsPerSheet: 8,
    columns: 2,
    rows: 4,
    isSticker: true,
    description: '4.0" × 2.0" adhesive label (8/sheet) for boxed lunches, grab-and-go catering containers, and salad bowls.',
    category: 'stickers',
  },
  {
    id: 'sticker-box-seal-4x3.33',
    name: 'Catering Box & Seal Sticker 4.0" × 3.33"',
    code: 'STK-4x3.33',
    shape: 'rounded-rect',
    widthIn: 4.0,
    heightIn: 3.33,
    cornerRadius: 6,
    cardsPerSheet: 6,
    columns: 2,
    rows: 3,
    isSticker: true,
    description: 'Large 4.0" × 3.33" label (6/sheet) for family-style catering boxes, charcuterie platters, and package sealing.',
    category: 'stickers',
  },
  {
    id: 'sticker-prep-2.6x1',
    name: 'Kitchen Prep & Jar Label 2.625" × 1.0"',
    code: 'STK-2.6x1',
    shape: 'rounded-rect',
    widthIn: 2.625,
    heightIn: 1.0,
    cornerRadius: 4,
    cardsPerSheet: 30,
    columns: 3,
    rows: 10,
    isSticker: true,
    description: 'High-density 2.625" × 1.0" label (30/sheet) for kitchen prep dates, chef rotation tags, squeeze bottles, and deli jars.',
    category: 'stickers',
  },
  {
    id: 'sticker-round-2.0',
    name: 'Round Seal Sticker 2.0" Dia',
    code: 'STK-RND-2',
    shape: 'circle',
    widthIn: 2.0,
    heightIn: 2.0,
    cornerRadius: 9999,
    cardsPerSheet: 12,
    columns: 3,
    rows: 4,
    isSticker: true,
    description: '2.0" diameter circular adhesive sticker (12/sheet) for bakery bags, sandwich wraps, and lid tamper seals.',
    category: 'stickers',
  },

  // --- Specialty Shapes & Badges ---
  {
    id: 'square-card-2.5x2.5',
    name: 'Square Tag & Platter Card 2.5" × 2.5"',
    code: 'SQ-2.5x2.5',
    shape: 'square',
    widthIn: 2.5,
    heightIn: 2.5,
    cornerRadius: 6,
    cardsPerSheet: 9,
    columns: 3,
    rows: 3,
    description: '2.5" × 2.5" modern square cards (9/sheet) for charcuterie, cheese boards, and hors d\'oeuvre platters.',
    category: 'shapes',
  },
  {
    id: 'circle-badge-2.5',
    name: 'Round Badge & Platter Tag 2.5" Dia',
    code: 'RND-2.5',
    shape: 'circle',
    widthIn: 2.5,
    heightIn: 2.5,
    cornerRadius: 9999,
    cardsPerSheet: 9,
    columns: 3,
    rows: 3,
    description: '2.5" diameter circular round tags for platter rings, soup cauldrons, and dessert stands.',
    category: 'shapes',
  },
  {
    id: 'oval-card-3.25x2',
    name: 'Oval Platter Label 3.25" × 2.0"',
    code: 'OVAL-3.25x2',
    shape: 'oval',
    widthIn: 3.25,
    heightIn: 2.0,
    cornerRadius: 9999,
    cardsPerSheet: 8,
    columns: 2,
    rows: 4,
    description: '3.25" × 2.0" elegant oval cards for wine bottles, silver cloches, and pastry platters.',
    category: 'shapes',
  },
  {
    id: 'imprintplus-012365-oval',
    name: 'Imprint Plus 012365 Oval 5.33" × 2.33" (3/sheet)',
    code: 'IMPRINT-012365',
    shape: 'oval',
    widthIn: 5.33,
    heightIn: 2.33,
    cornerRadius: 9999,
    cardsPerSheet: 3,
    columns: 1,
    rows: 3,
    isSticker: true,
    description: 'Imprint Plus Product #012365: 5.33" wide × 2.33" high landscape oval labels (3 per sheet). Calibrated for standard 8.5" × 11" sheet printers.',
    category: 'shapes',
  },
  {
    id: 'dome-arch-semi',
    name: 'Arch Dome Silhouette Stand 3.0" × 2.5"',
    code: 'ARCH-3x2.5',
    shape: 'semi-circle',
    widthIn: 3.0,
    heightIn: 2.5,
    cornerRadius: 0,
    cardsPerSheet: 6,
    columns: 2,
    rows: 3,
    description: 'Architectural arched top dome silhouette for luxury wedding buffets and floral displays.',
    category: 'shapes',
  },
  {
    id: 'large-display-4x3',
    name: 'Large Display Card 4.0" × 3.0"',
    code: 'CARD-4x3',
    shape: 'rectangle',
    widthIn: 4.0,
    heightIn: 3.0,
    cornerRadius: 4,
    cardsPerSheet: 4,
    columns: 2,
    rows: 2,
    description: 'Large 4.0" × 3.0" display cards for chafing dishes, soup cauldrons, and centerpiece carving stations.',
    category: 'cards',
  },
  {
    id: 'custom-template',
    name: 'Custom Dimensions & Layout',
    code: 'CUSTOM',
    shape: 'custom',
    widthIn: 3.5,
    heightIn: 2.0,
    cornerRadius: 8,
    cardsPerSheet: 10,
    columns: 2,
    rows: 5,
    description: 'Fully customizable width, height, corner radius, and sheet layout for any paper stock or adhesive label sheet.',
    category: 'custom',
  },
];

export const getTemplateById = (id: string): PrintTemplate => {
  return TEMPLATES.find((t) => t.id === id) || TEMPLATES[0]; // Default Standard Cardstock 3.5x2
};

/**
 * Calculates how many cards fit on standard 8.5" x 11" Letter page
 * with standard print safe margins (0.35" - 0.4" margin all around)
 */
export const calculateSheetLayout = (
  widthIn: number,
  heightIn: number,
  gapIn: number = 0.1
) => {
  const printableWidth = 8.5 - 0.6; // ~7.9 inches
  const printableHeight = 11.0 - 0.6; // ~10.4 inches

  const cols = Math.max(1, Math.floor((printableWidth + gapIn) / (widthIn + gapIn)));
  const rows = Math.max(1, Math.floor((printableHeight + gapIn) / (heightIn + gapIn)));
  const totalCards = cols * rows;

  return {
    columns: cols,
    rows: rows,
    cardsPerSheet: totalCards,
  };
};
